name: Ci

on: 
  workflow_dispatch:
    branches: [ "master" ]

jobs:
  build:
    name: build
    # if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with: 
          node-version: 16
      - name: Install dependencies
        run:
          yarn

      - name: Build for production
        run:
          yarn build:prod
      - name: Upload files to server
        run: |
          echo "Uploading files to server..."
          rsync -avz --progress \
          -e "sshpass -p ${{ secrets.SERVER_IP_PWD }}"  
          ./dist/* root@${{ secrets.SERVER_IP }}:'/home/app/testFolder/zllms-ui/dist'
          # /本地目录/ 用户名@阿里云服务器IP地址:/远程服务器目录/
          ./dist/* root@101.42.157.41:/home/app/zllms/admin-page/dist1
