name: Ci

on: 
  workflow_dispatch:
    # branches:
      # - master

jobs:
  build:
    name: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with: 
          node-version: 16
      - name: Install dependencies
        run:
          yarn

      - name: Build for production
        run:
          yarn build:prod

      - name: Run upload command
        run: yarn upload
        env:
          USERNAME: root
          PASSWORD: ${{ secrets.UPLOAD_PASSWORD }}
          SERVER: ${{ secrets.SERVER_IP }}
          REMOTE_PATH: /home/app/testFolder/zllms-ui/dist