name: Ci

on: 
  workflow_dispatch:
    branches: [ "master" ]

jobs:
  build:
    name: build
    # if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with: 
          node-version: 16
      - name: Install dependencies
        run:
          yarn

      - name: Build for production
        run:
          yarn build:prod
      - name: Deploy
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: |
      - name: Deploy aliyun
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-avz --delete"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.SERVER_IP }}
          REMOTE_USER: "root"
          TARGET: "/home/app/testFolder/zllms-ui/dist"
          SCRIPT_AFTER: |
            cd /home/app/testFolder/zllms-ui/ && rm -rf dist && mv dist1 dist